#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp -r 0/z.orig 0/z
cp -r 0/grad_z.orig 0/grad_z

runApplication blockMesh 
$application 


#------------------------------------------------------------------------------
